
#define DONT_USE_GENERATE_CODE                                                                 
//------------------------------------------------------------------------------                 
// <auto-generated>                                                                              
//     This code was generated by Lockstep.CodeGenerator                                         
//                                                                                               
//     Changes to this file may cause incorrect behavior and will be lost if                     
//     the code is regenerated.                                                                  
//     https://github.com/JiepengTan/LockstepPlatform                                            
// </auto-generated>                                                                             
//------------------------------------------------------------------------------                 
                                                                                                 
using Lockstep.Serialization;                                                                    
namespace Lockstep.BehaviourTree{                                                                            
#if !DONT_USE_GENERATE_CODE                                                                      

    [System.Serializable]                                                                           
    public partial class BTActionLoop{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTActionNonPrioritizedSelector{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTActionParallel{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTActionPrioritizedSelector{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTActionSequence{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTComposite{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTConditionFalse{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTConditionTrue{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTPreconditionAnd{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTPreconditionNot{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTPreconditionOr{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              

    [System.Serializable]                                                                           
    public partial class BTPreconditionXor{                                                                  
       public override void Serialize(Serializer writer){                                           
                                                                                     
       }                                                                                            
                                                                                                    
       public override void Deserialize(Deserializer reader){                                       
                                                                                     
       }                                                                                            
    }                                                                                              
                                                                              
#endif                                                                                           
}                                                                                               